# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSlEYw4D91pZ_phv-9v00_w9ic5yjG_0

1)Weather modelling using the quadratic equation
"""

a=5
b=4
c=6
x=4.5
y=a*x*x+b*x+c
print('The value of y is ',y)