# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSlEYw4D91pZ_phv-9v00_w9ic5yjG_0
"""

a=float(input('a='))
b=float(input('b='))
c=float(input('c='))
x=float(input('x='))
y=a*x*x+b*x+c
print('The value of y is ',y)